version: '3.8'

services:
  search-redirect:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9873:9876"
    volumes:
      - ./config.yml:/app/config.yml:ro
    environment:
      - CONFIG_PATH=/app/config.yml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s 