# fly.toml app configuration file generated for csh-search-api on 2025-02-28T18:36:57+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'csh-search-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 9876
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
